### ISSUE TITLE
\ior_map_inline:Nn doesn't match the documentation

### ISSUE THREAD

**Issue by eg9** [latex3/latex3#369]
The documentation about `\ior_map_inline:Nn` and `\ior_str_map_inline:Nn` states

> Note that TeX removes trailing space and tab characters (character codes 32 and 9) from every line upon input. TeX also ignores any trailing new-line marker from the file it reads.

However this is only true for `\ior_str_map_inline:Nn` as the following example shows

    \begin{filecontents*}{\jobname.lines}
    abc
    def
    
    ghi
    \end{filecontents*}
    
    \documentclass{article}
    \usepackage{xparse}
    
    \ExplSyntaxOn
    \NewDocumentCommand{\testA}{}
     {
      \ior_open:Nn \test_input_stream { \c_sys_jobname_str.lines }
      \ior_map_inline:Nn \test_input_stream
       {
        X##1X
       }
      \ior_close:N \test_input_stream
     }
    \NewDocumentCommand{\testB}{}
     {
      \ior_open:Nn \test_input_stream { \c_sys_jobname_str.lines }
      \ior_str_map_inline:Nn \test_input_stream
       {
        X##1X
       }
      \ior_close:N \test_input_stream
     }
    \ior_new:N \test_input_stream
    \ExplSyntaxOff
    
    \begin{document}
    
    \section{Test A}
    
    \testA
    
    \section{Test B}
    
    \testB
    
    \end{document}

![screen shot 2017-05-23 at 10 34 33](https://cloud.githubusercontent.com/assets/302839/26345523/75b48eb2-3fa3-11e7-95c2-c310214dcc4e.png)

**Comment by blefloch** [comment]
Haven't tested yet but this is mostly a documentation bug.  We should also document that `\read` continues reading lines until finding some token list that is brace-balanced so that it can return it (I remember some weird outcomes when the file ends early or perhaps with `\outer` macros).

- It is true that TeX discards trailing spaces and tabs from lines as soon as it reads the line (as part of the `\r\n`, `\r`, `\n` normalization).

- However, TeX still inserts the `\endlinechar` character, which typically is tokenized as if it were a space.

**Comment by eg9** [comment]
The important thing is that the documentation matches the behavior; trailing spaces can be easily  removed with `\tl_trim_spaces:n`

**Comment by blefloch** [comment]
Fixed in SVN revision 7210 by correcting the doc (sorry I forgot to put `fixes #369` in the commit comment).

**Comment by frougon** [comment]
Dear LaTeX3 maintainers,

I'm afraid this issue isn't solved: the diff for Git commit 7bd75d6b6b84a0a375c4c727b61735fa07a1b4ec (which, I believe, corresponds to SVN revision 7210) contains this chunk for `\ior_map_inline:Nn` in l3file.dtx:

```
-%   Applies the \meta{inline function} to \meta{lines} obtained by
-%   reading one or more lines (until an equal number of left and right
-%   braces are found) from the \meta{stream}. The \meta{inline function}
-%   should consist of code which will receive the \meta{line} as |#1|.
-%   Note that \TeX{} removes trailing space and tab characters
-%   (character codes 32 and 9) from every line upon input.  \TeX{} also
-%   ignores any trailing new-line marker from the file it reads.
+%   Applies the \meta{inline function} to each set of \meta{lines}
+%   obtained by calling \cs{ior_get:NN} until reaching the end of the
+%   file.  \TeX{} ignores any trailing new-line marker from the file it
+%   reads.  The \meta{inline function} should consist of code which will
+%   receive the \meta{line} as |#1|.
```

As a result, the documentation of `\ior_map_inline:Nn` still says:

> TeX ignores any trailing new-line marker from the file it reads

which appears to be incorrect, as shown by the example posted [by eg9 at the top of this report](https://github.com/latex3/latex3/issues/369#issue-230629092).

Thanks for looking into it!
